services:
  - type: web
    name: intelligent-query-backend
    env: python
    runtime: python-3.11.4
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
